language: java

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: required

services:
  - docker

script:
  - "mvn test"
  - "bash ./cmd/docker_test.sh"
  - "bash ./cmd/docker_test_selenium.sh"