FROM jenkins

MAINTAINER Viegas Mickael <mviegas@excilys.com>

COPY config/jenkins/plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt

COPY config/jenkins/config.xml /var/jenkins_home/jobs/docker-test/

USER root
RUN chown -R jenkins:jenkins /var/jenkins_home/jobs/
RUN chown -R jenkins:jenkins /var/jenkins_home/jobs/docker-test

# installation de docker client
RUN cd /tmp && \
    wget https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz && \
    tar zxvf docker-latest.tgz -C / && \
    rm docker-latest.tgz

#Installation de docke-compose
RUN curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    docker-compose --version


#RUN curl -fsSL https://get.docker.com/ | sh
#RUN usermod -aG docker root
#RUN usermod -aG docker jenkins

ENV DOCKER_HOST tcp://docker:2375
#USER jenkins