FROM jenkins

MAINTAINER Viegas Mickael <mviegas@excilys.com>

COPY config/jenkins/plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt

COPY config/jenkins/config.xml /var/jenkins_home/jobs/docker-test/

USER root
RUN chown -R jenkins:jenkins /var/jenkins_home/jobs/
RUN chown -R jenkins:jenkins /var/jenkins_home/jobs/docker-test

RUN cd /tmp && \
    wget https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz && \
    tar zxvf docker-latest.tgz -C / && \
    rm docker-latest.tgz


#RUN curl -fsSL https://get.docker.com/ | sh
#RUN usermod -aG docker root
#RUN usermod -aG docker jenkins

ENV DOCKER_HOST tcp://doocker:2375
#USER jenkins