FROM java:8

MAINTAINER Viegas Mickael <mviegas@excilys.com>

ENV DOWNLOAD http://www.h2database.com/h2-2016-01-21.zip
ENV DATA_DIR /opt/h2-data

ENV H2_PORT_WEB 81
ENV H2_PORT_TCP 1521

RUN curl ${DOWNLOAD} -o h2.zip \
    && unzip h2.zip -d /opt/ \
    && rm h2.zip \
    && mkdir -p ${DATA_DIR}

EXPOSE ${H2_PORT_WEB} ${H2_PORT_TCP}

COPY ./config/db/init.sql /docker-entrypoint-initdb.d/1.sql
COPY ./webapp-front/src/test/resources/db/1-SCHEMA.sql /docker-entrypoint-initdb.d/2.sql
COPY ./webapp-front/src/test/resources/db/3-ENTRIES.sql /docker-entrypoint-initdb.d/3.sql

RUN java -cp /opt/h2/bin/h2*.jar org.h2.tools.RunScript -url "jdbc:h2:~/test" -user "sa" -script "/docker-entrypoint-initdb.d/2.sql"
RUN java -cp /opt/h2/bin/h2*.jar org.h2.tools.RunScript -url "jdbc:h2:~/test" -user "sa" -script "/docker-entrypoint-initdb.d/3.sql"

CMD java -cp "/opt/h2/bin/*" org.h2.tools.Server \
 	-web -webAllowOthers -webPort ${H2_PORT_WEB} \
 	-tcp -tcpAllowOthers -tcpPort ${H2_PORT_TCP}