FROM java:8

MAINTAINER Viegas Mickael <mviegas@excilys.com>

ENV DOWNLOAD http://www.h2database.com/h2-2016-01-21.zip
ENV DATA_DIR /opt/h2-data

ENV H2_PORT_WEB 81
ENV H2_PORT_TCP 1521

RUN curl ${DOWNLOAD} -o h2.zip \
    && unzip h2.zip -d /opt/ \
    && rm h2.zip \
    && mkdir -p ${DATA_DIR}

EXPOSE ${H2_PORT_WEB} ${H2_PORT_TCP}

CMD java -cp "/opt/h2/bin/*" org.h2.tools.Server \
 	-web -webAllowOthers -webPort ${H2_PORT_WEB} \
 	-tcp -tcpAllowOthers -tcpPort ${H2_PORT_TCP} \
 	-baseDir ${DATA_DIR}